language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: deploy@peter-gribanov.ru

before_install:
    - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'
    - composer self-update
    - mkdir build

install:
    - composer install --no-interaction --no-progress

script:
    - vendor/bin/phpunit

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
